---
# example for update only glibc
##  - name: Update to latest state 
##    yum: name={{ item }} state=latest
##    with_items:
##     - glibc

# fix problem with filesyetm package on centos 7
- name: ensure that filesystem package will be upgraded
  lineinfile:
    dest: '/etc/rpm/macros.dist'
    line: '%_netsharedpath /sys:/proc'
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == '7'

# dependencies for CentOS LXC hypervisor host
- name: Install provisioning host dependencies
  yum: 
    name: "{{ item }}" 
    state: latest
  with_items:
  - python2-pip
  - gcc
  - python-devel
  - lxc-devel
  when: ansible_distribution == "CentOS"

# dependencies for Debian LXC hypervisor host
- name: Install provisioning host dependencies
  apt: 
    name: "{{ item }}" 
    update_cache: yes
    state: latest
  with_items:
  - python2-pip
  - gcc
  - python-dev
  - lxc-dev
  when: ansible_distribution == "Debian"


- name: dependencies for ansible lxc module
  pip:
    name: lxc-python2
  delegate_to: localhost
  when: ansible_virtualization_type == "lxc"

# upgrade all packages
- name: upgrade all packages
  yum: 
    name: '*' 
    state: latest
  notify:
  - Restart server if not lxc container
  - Restart lxc container 
  - Wait for server to restart
