---
# fix problem with filesyetm package on centos 7
- name: ensure that filesystem package will be upgraded
  lineinfile:
    dest: '/etc/rpm/macros.dist'
    line: '%_netsharedpath /sys:/proc'
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == '7'

# set fact for localhost ansible client
- name: Save os from ansible client
  setup:
    gather_subset: '!all'
  delegate_to: localhost
  delegate_facts: true
    
# dependencies for CentOS LXC hypervisor host
- name: Install provisioning CentOS LXC hypervisor host dependencies
  yum: 
    name: "{{ item }}" 
    state: latest
  with_items:
  - python2-pip
  - gcc
  - python-devel
  - lxc-devel
  delegate_to: localhost
  when: hostvars['localhost'].ansible_distribution == "CentOS" and ansible_virtualization_type == "lxc" and yum_update_autorestart
  
# dependencies for Debian LXC hypervisor host
- name: Install provisioning Debian LXC hypervisor host dependencies
  apt: 
    name: "{{ item }}" 
    update_cache: yes
    state: latest
  with_items:
  - python-pip
  - gcc
  - python-dev
  - lxc-dev
  delegate_to: localhost
  when: hostvars['localhost'].ansible_distribution == "Debian" and ansible_virtualization_type == "lxc" and yum_update_autorestart

# module to manage LXC containers
- name: dependencies for ansible lxc module
  pip:
    name: lxc-python2
  delegate_to: localhost
  when: ansible_virtualization_type == "lxc" and yum_update_autorestart

# upgrade all packages
- name: upgrade all packages
  yum: 
    name: '*' 
    state: latest
  notify:
  - Restart server if not lxc container
  - Restart lxc container 
  - Wait for server to restart
