---
# example for update only glibc
##  - name: Update to latest state 
##    yum: name={{ item }} state=latest
##    with_items:
##     - glibc

# fix problem with filesyetm package on centos 7
- name: ensure that filesystem package will be upgraded
  lineinfile:
    dest: '/etc/rpm/macros.dist'
    line: '%_netsharedpath /sys:/proc'
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == '7'

# set fact for localhost ansible client
- name: Save os from ansible client
  set_fact:
    local_distribution: "{{ ansible_distribution }}"
    delegate_to: localhost
    delegate_facts: True
    
# debug local_distribution
- name: Debug local_distribution fact
  debug:
    var: local_distribution

# dependencies for CentOS LXC hypervisor host
- name: Install provisioning host dependencies
  yum: 
    name: "{{ item }}" 
    state: latest
  with_items:
  - python2-pip
  - gcc
  - python-devel
  - lxc-devel
  delegate_to: localhost
  when: local_distribution == "CentOS" and ansible_virtualization_type == "lxc"
  
# dependencies for Debian LXC hypervisor host
- name: Install provisioning host dependencies
  apt: 
    name: "{{ item }}" 
    update_cache: yes
    state: latest
  with_items:
  - python2-pip
  - gcc
  - python-dev
  - lxc-dev
  delegate_to: localhost
  when: local_distribution == "Debian" and ansible_virtualization_type == "lxc"

# module to manage LXC containers
- name: dependencies for ansible lxc module
  pip:
    name: lxc-python2
  delegate_to: localhost
  when: ansible_virtualization_type == "lxc"

# upgrade all packages
- name: upgrade all packages
  yum: 
    name: '*' 
    state: latest
  notify:
  - Restart server if not lxc container
  - Restart lxc container 
  - Wait for server to restart
